import { Injectable } from '@angular/core';
import { Room } from '../models/room.model';
import { RoomTypeService } from './room-type.service';

@Injectable({
  providedIn: 'root',
})
export class RoomService {
  constructor(private roomTypeService: RoomTypeService) {}

  getRooms(): Room[] {
    return this.rooms;
  }

  getRoomById(id: number): Room | undefined {
    return this.rooms.find((item) => item.id === id);
  }

  getRoomsByTypeId(typeId: number): Room[] {
    return this.rooms.filter((room) => room.roomType.id === typeId);
  }

  private get rooms(): Room[] {
    return [
    {
      id: 1,
      number: '101',
      floor: 1,
      roomType: this.roomTypeService.getRoomTypeById(1)!,
      status: 'AVAILABLE',
      name: 'Deluxe Room',
      capacity: 2,
      bedType: 'King Size',
      area: 30,
      pricePerNight: 80.0,
      heroDescription:
        'Una habitación diseñada para quienes buscan el equilibrio perfecto entre lujo discreto y confort absoluto. Materiales nobles, iluminación cálida y vistas que invitan al descanso.',
      headline: 'El refugio perfecto para un descanso revitalizante',
      fullDescription:
        'Nuestra Deluxe Room combina un diseño contemporáneo con toques clásicos europeos. Suelos de roble, ropa de cama de algodón egipcio de 400 hilos, minibar premium y un baño revestido en mármol de Carrara con ducha de efecto lluvia.',
      secondaryImageUrl:
        'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80',
      highlights: [
        {
          title: 'Cama King Size con colchón premium',
          description:
            'Colchón de muelles ensacados con topper de pluma de ganso para un descanso reparador.',
        },
        {
          title: 'Baño en mármol con ducha efecto lluvia',
          description:
            'Amenities de cortesía Hermès y albornoz de algodón turco.',
        },
        {
          title: 'Smart TV 55" y WiFi de alta velocidad',
          description:
            'Acceso a plataformas de streaming y conectividad empresarial.',
        },
        {
          title: 'Servicio de habitaciones 24 horas',
          description:
            'Carta gourmet disponible a cualquier hora con presentación impecable.',
        },
      ],
      galleryImages: [
        'https://images.unsplash.com/photo-1590490360182-c33d955c4644?auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=800&q=80',
      ],
    },
    {
      id: 2,
      number: '102',
      floor: 1,
      roomType: this.roomTypeService.getRoomTypeById(2)!,
      status: 'AVAILABLE',
      name: 'Premium Suite',
      capacity: 2,
      bedType: 'King Size',
      area: 30,
      pricePerNight: 116.52,
      heroDescription:
        'Un espacio generoso donde la elegancia se funde con la funcionalidad. Sala de estar independiente, balcón privado y vistas panorámicas al Mediterráneo.',
      headline: 'Amplitud y sofisticación con vistas al horizonte',
      fullDescription:
        'La Premium Suite ofrece una experiencia elevada con sala de estar separada, escritorio ejecutivo, vestidor walk-in y un balcón privado con mobiliario de exterior premium. Ideal para estancias prolongadas o viajeros que valoran el espacio.',
      secondaryImageUrl:
        'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?auto=format&fit=crop&w=800&q=80',
      highlights: [
        {
          title: 'Sala de estar independiente',
          description:
            'Sofá de diseño italiano, mesa de centro y biblioteca curada.',
        },
        {
          title: 'Balcón privado con vistas al mar',
          description:
            'Mobiliario de exterior y servicio de desayuno al aire libre.',
        },
        {
          title: 'Vestidor walk-in iluminado',
          description:
            'Espacio amplio con perchas de cedro y caja fuerte de gran formato.',
        },
        {
          title: 'Máquina Nespresso y minibar premium',
          description:
            'Selección de cápsulas de origen único y bebidas artesanales.',
        },
      ],
      galleryImages: [
        'https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1560448204-603b3fc33ddc?auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=80',
      ],
    },
    {
      id: 3,
      number: '103',
      floor: 1,
      roomType: this.roomTypeService.getRoomTypeById(3)!,
      status: 'AVAILABLE',
      name: 'Grand Suite',
      capacity: 4,
      bedType: 'King Size',
      area: 60,
      pricePerNight: 200.0,
      heroDescription:
        'La máxima expresión del lujo residencial. Espacios amplios con decoración de autor, comedor privado y una terraza que domina la costa del Principado.',
      headline: 'Donde el lujo se convierte en un estilo de vida',
      fullDescription:
        'La Grand Suite redefine la hospitalidad con más de 80 m² de espacio habitable. Dormitorio principal con vestidor, segundo dormitorio opcional, comedor para cuatro personas, baño doble con bañera exenta y terraza panorámica privada.',
      secondaryImageUrl:
        'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=800&q=80',
      highlights: [
        {
          title: 'Dos dormitorios con opción de conectar',
          description:
            'Configuración flexible para familias o comitivas ejecutivas.',
        },
        {
          title: 'Comedor privado para 4 personas',
          description:
            'Mesa de mármol con servicio de chef privado bajo petición.',
        },
        {
          title: 'Bañera exenta y doble lavabo',
          description:
            'Bañera de piedra natural con sales aromáticas de cortesía.',
        },
        {
          title: 'Terraza panorámica de 20 m²',
          description:
            'Tumbonas, sombrilla y servicio de cócteles al atardecer.',
        },
      ],
      galleryImages: [
        'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1540518614846-7eded433c457?auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1564078516393-cf04bd966897?auto=format&fit=crop&w=800&q=80',
      ],
    },
    {
      id: 4,
      number: '104',
      floor: 1,
      roomType: this.roomTypeService.getRoomTypeById(4)!,
      status: 'AVAILABLE',
      name: 'Suite Royale',
      capacity: 4,
      bedType: 'King Size',
      area: 60,
      pricePerNight: 280.0,
      heroDescription:
        'Reservada para los huéspedes más distinguidos. Un santuario privado con mayordomo dedicado, acceso directo al spa y los más altos estándares de discreción.',
      headline: 'La experiencia definitiva en hospitalidad de autor',
      fullDescription:
        'La Suite Royale es nuestra joya. Decorada con piezas de arte originales, chimenea de bioetanol, piano de cola Steinway y un jacuzzi privado en la terraza. Incluye servicio de mayordomo 24h y check-in privado.',
      secondaryImageUrl:
        'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=800&q=80',
      highlights: [
        {
          title: 'Mayordomo personal 24 horas',
          description: 'Atención exclusiva para cada detalle de tu estancia.',
        },
        {
          title: 'Jacuzzi privado en terraza',
          description:
            'Hidromasaje con vistas al Mediterráneo y servicio de champán.',
        },
        {
          title: 'Obras de arte originales',
          description:
            'Colección curada de artistas contemporáneos del Principado.',
        },
        {
          title: 'Check-in y check-out privado',
          description: 'Recepción en suite con champagne de bienvenida Krug.',
        },
      ],
      galleryImages: [
        'https://images.unsplash.com/photo-1611892440504-42a792e24d32?auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1591088398332-8a7791972843?auto=format&fit=crop&w=800&q=80',
      ],
    },
    {
      id: 5,
      number: '105',
      floor: 1,
      roomType: this.roomTypeService.getRoomTypeById(5)!,
      status: 'AVAILABLE',
      name: 'Suite Royale',
      capacity: 4,
      bedType: 'King Size',
      area: 60,
      pricePerNight: 350.0,
      highlights: [],
      galleryImages: [],
    },
    {
      id: 6,
      number: '106',
      floor: 1,
      roomType: this.roomTypeService.getRoomTypeById(1)!,
      status: 'AVAILABLE',
      name: 'Simple',
      capacity: 2,
      bedType: 'King Size',
      area: 30,
      pricePerNight: 80.0,
      highlights: [],
      galleryImages: [],
    },
    {
      id: 7,
      number: '107',
      floor: 1,
      roomType: this.roomTypeService.getRoomTypeById(2)!,
      status: 'OCCUPIED',
      name: 'Deluxe',
      capacity: 2,
      bedType: 'King Size',
      area: 30,
      pricePerNight: 116.52,
      highlights: [],
      galleryImages: [],
    },
    {
      id: 8,
      number: '108',
      floor: 1,
      roomType: this.roomTypeService.getRoomTypeById(3)!,
      status: 'AVAILABLE',
      name: 'Suite',
      capacity: 4,
      bedType: 'King Size',
      area: 60,
      pricePerNight: 200.0,
      highlights: [],
      galleryImages: [],
    },
    {
      id: 9,
      number: '109',
      floor: 1,
      roomType: this.roomTypeService.getRoomTypeById(4)!,
      status: 'AVAILABLE',
      name: 'Premium Suite',
      capacity: 4,
      bedType: 'King Size',
      area: 60,
      pricePerNight: 280.0,
      highlights: [],
      galleryImages: [],
    },
    {
      id: 10,
      number: '110',
      floor: 1,
      roomType: this.roomTypeService.getRoomTypeById(5)!,
      status: 'AVAILABLE',
      name: 'Suite Royale',
      capacity: 4,
      bedType: 'King Size',
      area: 60,
      pricePerNight: 350.0,
      highlights: [],
      galleryImages: [],
    },
    {
      id: 11,
      number: '111',
      floor: 2,
      roomType: this.roomTypeService.getRoomTypeById(1)!,
      status: 'AVAILABLE',
      name: 'Simple',
      capacity: 2,
      bedType: 'King Size',
      area: 30,
      pricePerNight: 80.0,
      highlights: [],
      galleryImages: [],
    },
    {
      id: 12,
      number: '112',
      floor: 2,
      roomType: this.roomTypeService.getRoomTypeById(2)!,
      status: 'AVAILABLE',
      name: 'Deluxe',
      capacity: 2,
      bedType: 'King Size',
      area: 30,
      pricePerNight: 116.52,
      highlights: [],
      galleryImages: [],
    },
    {
      id: 13,
      number: '113',
      floor: 2,
      roomType: this.roomTypeService.getRoomTypeById(3)!,
      status: 'AVAILABLE',
      name: 'Suite',
      capacity: 4,
      bedType: 'King Size',
      area: 60,
      pricePerNight: 200.0,
      highlights: [],
      galleryImages: [],
    },
    {
      id: 14,
      number: '114',
      floor: 2,
      roomType: this.roomTypeService.getRoomTypeById(4)!,
      status: 'OCCUPIED',
      name: 'Premium Suite',
      capacity: 4,
      bedType: 'King Size',
      area: 60,
      pricePerNight: 280.0,
      highlights: [],
      galleryImages: [],
    },
    {
      id: 15,
      number: '115',
      floor: 2,
      roomType: this.roomTypeService.getRoomTypeById(5)!,
      status: 'AVAILABLE',
      name: 'Suite Royale',
      capacity: 4,
      bedType: 'King Size',
      area: 60,
      pricePerNight: 350.0,
      highlights: [],
      galleryImages: [],
    },
    {
      id: 16,
      number: '116',
      floor: 2,
      roomType: this.roomTypeService.getRoomTypeById(1)!,
      status: 'AVAILABLE',
      name: 'Simple',
      capacity: 2,
      bedType: 'King Size',
      area: 30,
      pricePerNight: 80.0,
      highlights: [],
      galleryImages: [],
    },
    {
      id: 17,
      number: '117',
      floor: 2,
      roomType: this.roomTypeService.getRoomTypeById(2)!,
      status: 'AVAILABLE',
      name: 'Deluxe',
      capacity: 2,
      bedType: 'King Size',
      area: 30,
      pricePerNight: 116.52,
      highlights: [],
      galleryImages: [],
    },
    {
      id: 18,
      number: '118',
      floor: 2,
      roomType: this.roomTypeService.getRoomTypeById(3)!,
      status: 'AVAILABLE',
      name: 'Suite',
      capacity: 4,
      bedType: 'King Size',
      area: 60,
      pricePerNight: 200.0,
      highlights: [],
      galleryImages: [],
    },
    {
      id: 19,
      number: '119',
      floor: 2,
      roomType: this.roomTypeService.getRoomTypeById(4)!,
      status: 'AVAILABLE',
      name: 'Premium Suite',
      capacity: 4,
      bedType: 'King Size',
      area: 60,
      pricePerNight: 280.0,
      highlights: [],
      galleryImages: [],
    },
    {
      id: 20,
      number: '120',
      floor: 2,
      roomType: this.roomTypeService.getRoomTypeById(5)!,
      status: 'AVAILABLE',
      name: 'Suite Royale',
      capacity: 4,
      bedType: 'King Size',
      area: 60,
      pricePerNight: 350.0,
      highlights: [],
      galleryImages: [],
    },
    {
      id: 21,
      number: '121',
      floor: 3,
      roomType: this.roomTypeService.getRoomTypeById(1)!,
      status: 'OCCUPIED',
      name: 'Simple',
      capacity: 2,
      bedType: 'King Size',
      area: 30,
      pricePerNight: 80.0,
      highlights: [],
      galleryImages: [],
    },
    {
      id: 22,
      number: '122',
      floor: 3,
      roomType: this.roomTypeService.getRoomTypeById(2)!,
      status: 'AVAILABLE',
      name: 'Deluxe',
      capacity: 2,
      bedType: 'King Size',
      area: 30,
      pricePerNight: 116.52,
      highlights: [],
      galleryImages: [],
    },
    {
      id: 23,
      number: '123',
      floor: 3,
      roomType: this.roomTypeService.getRoomTypeById(3)!,
      status: 'AVAILABLE',
      name: 'Suite',
      capacity: 4,
      bedType: 'King Size',
      area: 60,
      pricePerNight: 200.0,
      highlights: [],
      galleryImages: [],
    },
    {
      id: 24,
      number: '124',
      floor: 3,
      roomType: this.roomTypeService.getRoomTypeById(4)!,
      status: 'AVAILABLE',
      name: 'Premium Suite',
      capacity: 4,
      bedType: 'King Size',
      area: 60,
      pricePerNight: 280.0,
      highlights: [],
      galleryImages: [],
    },
    {
      id: 25,
      number: '125',
      floor: 3,
      roomType: this.roomTypeService.getRoomTypeById(5)!,
      status: 'AVAILABLE',
      name: 'Suite Royale',
      capacity: 4,
      bedType: 'King Size',
      area: 60,
      pricePerNight: 350.0,
      highlights: [],
      galleryImages: [],
    },
    {
      id: 26,
      number: '126',
      floor: 3,
      roomType: this.roomTypeService.getRoomTypeById(1)!,
      status: 'AVAILABLE',
      name: 'Simple',
      capacity: 2,
      bedType: 'King Size',
      area: 30,
      pricePerNight: 80.0,
      highlights: [],
      galleryImages: [],
    },
    {
      id: 27,
      number: '127',
      floor: 3,
      roomType: this.roomTypeService.getRoomTypeById(2)!,
      status: 'AVAILABLE',
      name: 'Deluxe',
      capacity: 2,
      bedType: 'King Size',
      area: 30,
      pricePerNight: 116.52,
      highlights: [],
      galleryImages: [],
    },
    {
      id: 28,
      number: '128',
      floor: 3,
      roomType: this.roomTypeService.getRoomTypeById(3)!,
      status: 'OCCUPIED',
      name: 'Suite',
      capacity: 4,
      bedType: 'King Size',
      area: 60,
      pricePerNight: 200.0,
      highlights: [],
      galleryImages: [],
    },
    {
      id: 29,
      number: '129',
      floor: 3,
      roomType: this.roomTypeService.getRoomTypeById(4)!,
      status: 'AVAILABLE',
      name: 'Premium Suite',
      capacity: 4,
      bedType: 'King Size',
      area: 60,
      pricePerNight: 280.0,
      highlights: [],
      galleryImages: [],
    },
    {
      id: 30,
      number: '130',
      floor: 3,
      roomType: this.roomTypeService.getRoomTypeById(5)!,
      status: 'AVAILABLE',
      name: 'Suite Royale',
      capacity: 4,
      bedType: 'King Size',
      area: 60,
      pricePerNight: 350.0,
      highlights: [],
      galleryImages: [],
    },
    {
      id: 31,
      number: '131',
      floor: 4,
      roomType: this.roomTypeService.getRoomTypeById(1)!,
      status: 'AVAILABLE',
      name: 'Simple',
      capacity: 2,
      bedType: 'King Size',
      area: 30,
      pricePerNight: 80.0,
      highlights: [],
      galleryImages: [],
    },
    {
      id: 32,
      number: '132',
      floor: 4,
      roomType: this.roomTypeService.getRoomTypeById(2)!,
      status: 'AVAILABLE',
      name: 'Deluxe',
      capacity: 2,
      bedType: 'King Size',
      area: 30,
      pricePerNight: 116.52,
      highlights: [],
      galleryImages: [],
    },
    {
      id: 33,
      number: '133',
      floor: 4,
      roomType: this.roomTypeService.getRoomTypeById(3)!,
      status: 'AVAILABLE',
      name: 'Suite',
      capacity: 4,
      bedType: 'King Size',
      area: 60,
      pricePerNight: 200.0,
      highlights: [],
      galleryImages: [],
    },
    {
      id: 34,
      number: '134',
      floor: 4,
      roomType: this.roomTypeService.getRoomTypeById(4)!,
      status: 'AVAILABLE',
      name: 'Premium Suite',
      capacity: 4,
      bedType: 'King Size',
      area: 60,
      pricePerNight: 280.0,
      highlights: [],
      galleryImages: [],
    },
    {
      id: 35,
      number: '135',
      floor: 4,
      roomType: this.roomTypeService.getRoomTypeById(5)!,
      status: 'OCCUPIED',
      name: 'Suite Royale',
      capacity: 4,
      bedType: 'King Size',
      area: 60,
      pricePerNight: 350.0,
      highlights: [],
      galleryImages: [],
    },
    {
      id: 36,
      number: '136',
      floor: 4,
      roomType: this.roomTypeService.getRoomTypeById(1)!,
      status: 'AVAILABLE',
      name: 'Simple',
      capacity: 2,
      bedType: 'King Size',
      area: 30,
      pricePerNight: 80.0,
      highlights: [],
      galleryImages: [],
    },
    {
      id: 37,
      number: '137',
      floor: 4,
      roomType: this.roomTypeService.getRoomTypeById(2)!,
      status: 'AVAILABLE',
      name: 'Deluxe',
      capacity: 2,
      bedType: 'King Size',
      area: 30,
      pricePerNight: 116.52,
      highlights: [],
      galleryImages: [],
    },
    {
      id: 38,
      number: '138',
      floor: 4,
      roomType: this.roomTypeService.getRoomTypeById(3)!,
      status: 'AVAILABLE',
      name: 'Suite',
      capacity: 4,
      bedType: 'King Size',
      area: 60,
      pricePerNight: 200.0,
      highlights: [],
      galleryImages: [],
    },
    {
      id: 39,
      number: '139',
      floor: 4,
      roomType: this.roomTypeService.getRoomTypeById(4)!,
      status: 'AVAILABLE',
      name: 'Premium Suite',
      capacity: 4,
      bedType: 'King Size',
      area: 60,
      pricePerNight: 280.0,
      highlights: [],
      galleryImages: [],
    },
    {
      id: 40,
      number: '140',
      floor: 4,
      roomType: this.roomTypeService.getRoomTypeById(5)!,
      status: 'AVAILABLE',
      name: 'Suite Royale',
      capacity: 4,
      bedType: 'King Size',
      area: 60,
      pricePerNight: 350.0,
      highlights: [],
      galleryImages: [],
    },
    {
      id: 41,
      number: '141',
      floor: 5,
      roomType: this.roomTypeService.getRoomTypeById(1)!,
      status: 'AVAILABLE',
      name: 'Simple',
      capacity: 2,
      bedType: 'King Size',
      area: 30,
      pricePerNight: 80.0,
      highlights: [],
      galleryImages: [],
    },
    {
      id: 42,
      number: '142',
      floor: 5,
      roomType: this.roomTypeService.getRoomTypeById(2)!,
      status: 'OCCUPIED',
      name: 'Deluxe',
      capacity: 2,
      bedType: 'King Size',
      area: 30,
      pricePerNight: 116.52,
      highlights: [],
      galleryImages: [],
    },
    {
      id: 43,
      number: '143',
      floor: 5,
      roomType: this.roomTypeService.getRoomTypeById(3)!,
      status: 'AVAILABLE',
      name: 'Suite',
      capacity: 4,
      bedType: 'King Size',
      area: 60,
      pricePerNight: 200.0,
      highlights: [],
      galleryImages: [],
    },
    {
      id: 44,
      number: '144',
      floor: 5,
      roomType: this.roomTypeService.getRoomTypeById(4)!,
      status: 'AVAILABLE',
      name: 'Premium Suite',
      capacity: 4,
      bedType: 'King Size',
      area: 60,
      pricePerNight: 280.0,
      highlights: [],
      galleryImages: [],
    },
    {
      id: 45,
      number: '145',
      floor: 5,
      roomType: this.roomTypeService.getRoomTypeById(5)!,
      status: 'AVAILABLE',
      name: 'Suite Royale',
      capacity: 4,
      bedType: 'King Size',
      area: 60,
      pricePerNight: 350.0,
      highlights: [],
      galleryImages: [],
    },
    {
      id: 46,
      number: '146',
      floor: 5,
      roomType: this.roomTypeService.getRoomTypeById(1)!,
      status: 'AVAILABLE',
      name: 'Simple',
      capacity: 2,
      bedType: 'King Size',
      area: 30,
      pricePerNight: 80.0,
      highlights: [],
      galleryImages: [],
    },
    {
      id: 47,
      number: '147',
      floor: 5,
      roomType: this.roomTypeService.getRoomTypeById(2)!,
      status: 'AVAILABLE',
      name: 'Deluxe',
      capacity: 2,
      bedType: 'King Size',
      area: 30,
      pricePerNight: 116.52,
      highlights: [],
      galleryImages: [],
    },
    {
      id: 48,
      number: '148',
      floor: 5,
      roomType: this.roomTypeService.getRoomTypeById(3)!,
      status: 'AVAILABLE',
      name: 'Suite',
      capacity: 4,
      bedType: 'King Size',
      area: 60,
      pricePerNight: 200.0,
      highlights: [],
      galleryImages: [],
    },
    {
      id: 49,
      number: '149',
      floor: 5,
      roomType: this.roomTypeService.getRoomTypeById(4)!,
      status: 'OCCUPIED',
      name: 'Premium Suite',
      capacity: 4,
      bedType: 'King Size',
      area: 60,
      pricePerNight: 280.0,
      highlights: [],
      galleryImages: [],
    },
    {
      id: 50,
      number: '150',
      floor: 5,
      roomType: this.roomTypeService.getRoomTypeById(5)!,
      status: 'AVAILABLE',
      name: 'Suite Royale',
      capacity: 4,
      bedType: 'King Size',
      area: 60,
      pricePerNight: 350.0,
      highlights: [],
      galleryImages: [],
    },
    ];
  }
}

